[package]
name = "rusty_dierckx"
version = "0.1.0"
authors = ["Joscha Hoche joscha.hoche@uni-wuerzburg.de"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version = "0.12", features = ["serde-1"]}
